#!/bin/bash

exit_code=0

echo -e "\n=== Compiling node tests"

if ! clojure -A:test:compile-node-tests; then
    exit_code=1
fi

echo -e "\n=== Running node tests"

if ! node out/main.js; then
    exit_code=1
fi

exit $exit_code
