#!/bin/sh

set $exit_code=0

echo "\n=== Compiling node tests"
clojure -A:test:compile-node-tests
if [ $? != 0 ]; then
    exit_code=1
fi

echo "\n=== Running node tests"
node out/main.js
if [ $? != 0 ]; then
    exit_code=1
fi

exit $exit_code
