#!/bin/bash

if [ -n "$COAL_MINE_TIMEOUT" ]; then
    timeout=$(command -v timeout)
    if [ -z "$timeout" ]; then
        timeout=$(command -v gtimeout)
    fi

    if [ -z "$timeout" ]; then
        echo -e "WARNING: timeout program not found, running without it\n"
    else
        timeout_cmd="$timeout $COAL_MINE_TIMEOUT"
    fi
fi

problem=$1

echo -e "=== Generating coal-mine-runner"

rm -rf out
clojure -A:test:coal-mine:coal-mine-generator out/out.cljc ${problem:+"$problem"}

if [ "$SKIP_CLJ" != true ]; then
    echo -e "\n=== Running clj coal-mine tests"
    $timeout_cmd clojure -R:test:coal-mine:coal-mine-clj -i out/out.cljc \
        | tee -a out/output.txt
fi

if [ "$SKIP_CLJS" != true ]; then
    echo -e "\n=== Running cljs node coal-mine tests"
    $timeout_cmd clojure -R:test:coal-mine:coal-mine-cljs -m cljs.main -re node -i out/out.cljc \
        | tee -a out/output.txt
fi

if [ "$CI" = true ]; then
    errors=$(grep -c ERROR out/output.txt)
    if [ "$errors" -gt 0 ]; then
        problem=$(grep Testing out/output.txt | head -n 1 | sed 's/Testing //')
        msg="found speculative spec errors with problem $problem"
        curl -X POST -H "Content-Type: application/json" \
             -d '{"username":"speculative coal-mine test", "channel":"#speculative", "text":'"\"$msg\""'}' \
             "$SPECULATIVE_SLACK_HOOK"
    fi
fi
exit 0
