#!/bin/sh

timeout=$(command -v timeout)
if [ -z $timeout ]; then
    timeout=$(command -v gtimeout)
fi

if [ -z $timeout ]; then
    echo "WARNING: timeout program not found, running without it\n"
else
    timeout_cmd="$timeout 80"
fi

op=$1
if [ -z $op ]; then
   op="random"
fi

max_or_nth=$2
if [ -z $max_or_nth ]; then
    max_or_nth="1"
fi

echo "=== Generating coal-mine-runner"
clojure -A:test:coal-mine-generator out/out.cljc $op $max_or_nth

echo "\n=== Running clj coal-mine tests"
$timeout_cmd clojure -R:test:coal-mine-clj -i out/out.cljc

echo "\n=== Running cljs node coal-mine tests"
$timeout_cmd clojure -R:test:coal-mine-cljs -m cljs.main -re node -i out/out.cljc

exit 0
