#!/bin/sh

echo "=== Running clj cost calculations"
clojure -A:test:cost

echo "\n=== Running cljs node cost calculations"
clojure -A:test:cost:cljs-cost

# Tufte doesn't work on self-hosted yet
# echo "\n=== Running plk cost calculations"
# plk -A:test:cost
# if [ $? != 0 ]; then
#     exit_code=1
# fi
