#!/bin/bash

err=0
trap '(( err |= $? ))' ERR
trap 'exit $err' SIGINT SIGTERM

case "$TEST_ENV" in
    "clj") test_runner=clj-test-runner ;;
    "cljs") test_runner=cljs-test-runner ;;
    *) echo "Set TEST_ENV to either clj or cljs"; exit 1
esac

if [ "$TEST_ENV" = "cljs" ]; then
    case "$CLJS_ENV" in
        "node") ;;
        "planck") ;;
        *) echo "Set CLJS_ENV to either node or planck"; exit 1
    esac
fi

echo -e "\n==== Running $TEST_ENV${CLJS_ENV:+ $CLJS_ENV} unit tests ===="

clojure "-A:test:$test_runner"  \
        ${CLJS_ENV:+-x "$CLJS_ENV"} \
        -n speculative.test-prelude \
        -n speculative.core-test \
        -n speculative.specs-test \
        -n speculative.set-test \
        -n speculative.string-test

echo -e "\n==== Running $TEST_ENV${CLJS_ENV:+ $CLJS_ENV} instrumentation tests ===="

clojure "-A:test:$test_runner"  \
        ${CLJS_ENV:+-x "$CLJS_ENV"} \
        -n speculative.test-prelude \
        -n speculative.instrument-test

exit "$err"
