#!/bin/bash

script/clean
export SPECULATIVE_NO_UNLOAD_BLACKLIST=true

exit_code=0

echo "=== Running clj-tests"

if ! clojure -A:test:clj-tests; then
    exit_code=1
fi

if ! script/cljs-tests; then
    exit_code=1
fi

echo -e "\n=== Running plk-tests"

if ! plk -A:test:plk-tests; then
    exit_code=1
fi

exit $exit_code
